// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iquduvynsfrrugfhpzsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxdWR1dnluc2ZycnVnZmhwenNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjg2ODcsImV4cCI6MjA2MTYwNDY4N30.tvqZLbulTm5AmP8RMnNhJCXfQkga4ONVkJPaStUvfqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);